### PR TITLE
update fonts to new, unicode-range subset versions

### PR DESCRIPTION
**Pull request by arrowtype**
Hi Sia, I love your website! It's an amazing visual example of Recursive in use, in addition to having a ton of really great web dev writing. I'm so glad you chose to use Recursive for it!

Recursive has gotten a ton of little (and big) refinements in the months since you first chose it for your site, so I wanted to make a PR to hopefully make it easy to incorporate the improvements. 

## Background & Approach

You obviously don't want your site to go from the existing 135KB version load the 500+ KB woff2 with a full character set you won't need most of, so it took some time for me to get around figuring out a good system for subsetting things. I think I've found a pretty good solution!

So, this update makes use of the CSS property `unicode-range` to serve split subsets of Recursive, based on what unicodes a given page needs. This is based on the advice in [this CSS-Tricks article](https://css-tricks.com/three-techniques-performant-custom-font-usage/) plus some specific thought given to what additional symbols are really needed for "Basic English" in a code blog. I've broken things into basic english, Latin A letters, Latin A punctuation/symbols, and Latin Extended. This still leaves out quite a few characters from the final font, including more extended Latin (e.g. Vietnamese glyphs) and more symbols (e.g. a bunch of currency symbols, fractions, geometric symbols, etc etc).

It _also_ uses a variable axis subsetter to reduce the weight range to just 300–800, because I couldn't see any use of heavier weights outside of your name ("sia") on the homepage. For that specific word, this update also includes a 3-glyph static font which is 1.74KB. 

The upshot: on the homepage, you will typically load the main font file of 137KB plus the logo font of 1.74KB. Except...

One thing we could further improve: this actually currently also loads the 30KB "Latin A Punctuation" font on the homepage, but I'm not quite sure which symbol is causing this. If we can find whatever glyph is in "Latin A Punctuation" that makes this happen, we could move it over to the Basic English font to save about 30KB.

Here's my shell script to do this font splitting:
https://github.com/arrowtype/recursive/blob/18bb7ad2a1315c7cf71fe1753d9a01a5c995c08e/src/build-scripts/unicode-range-subsets-300_800.sh

## Why update?

**Missing characters**

When you built the site with the November 2019 subset of Recursive, I hadn't yet figured I proper strategy to subset the font, so that one just had a unicode "Basic Latin" range – which leaves out symbols used on many pages, such as ©, arrows, and curly/smart quotes. So, these are replaced with Arial, which isn't _horrible,_ but definitely isn't ideal.

In addition, it leaves out any Latin diacritics, which is unfortunate when you mention people with names like [`Max Böck`](http://localhost:8080/posts/webmentions-eleventy-in-depth/) or [`Sara Kurfeß`](http://localhost:8080/posts/conditional-twitter-intents-with-eleventy/).

image

image

**Old font bugs**

Back in November, the `pysubset` tool didn't quite work as needed for variable fonts with variable axis-based glyph substitutions. Recursive has a number of characters which change form in different – such as the `l` and `i` being different between sans, mono, and mono italic styles. Unfortunately, that old bug means that the code blocks all have sans-form glyphs, which look okay, but aren't quite optimized for the best spacing in code. Worse, I've noticed that the `fi` ligature has made it into some code blocks, which is definitely not intended.

image

**Various font improvements**

Example: 
- The specific November version in the current site accidentally leaves the mono-italic version of `l` in the Sans styles, which looks _okay_, but a little less clean than the simpler, current `l`.
- The mono-italic `f` is nicer.
- Probably lots of other subtle improvements that don't come to mind immediately.

## One extra fix

This fixes a Safari font rendering bug which double-italicizes things. It does so by removing the `font-style: italic` and only using `font-variation-settings`.

As-is:

image

Update:

image

(In the future, it might be slightly better to use `font-style: oblique -8deg` for better fallback/loading fonts, but Safari also doesn't support this properly, for now. So, `font-variation-settings` is the most consistent across browsers, at this time).

### CODE REVIEW

**Comment by arrowtype** [comment]
Shoot; I've realized that the Basic English subset includes fractions and sups/infs, which probably aren't very necessary. Let me see whether I can subset those out, and get these font files a bit smaller, still.

**Comment by arrowtype** [comment]
Okay, so, after another try, I can follow up on the two items that I was uncertain on in my earlier comments:

> One thing we could further improve: this actually currently also loads the 30KB "Latin A Punctuation" font on the homepage, but I'm not quite sure which symbol is causing this. If we can find whatever glyph is in "Latin A Punctuation" that makes this happen, we could move it over to the Basic English font to save about 30KB.

Even when I try to subset the basic english font to have _exactly_ the unicodes on the homepage (online or localhost versions) _and_ remove the © glyph from the Latin A Punctuation subset, Latin A Punctuation still loads. I'm not sure why.

> I've realized that the Basic English subset includes fractions and sups/infs, which probably aren't very necessary. Let me see whether I can subset those out, and get these font files a bit smaller, still.

I'm definitely not including sups/infs in my subset code, and yet they are ending up in the English Basic font (potentially because they are closely related to the normal figs through OpenType features `sups, numr, sinf, dnom`?). However, I was able to get fractions to get subset out.

Even with the Latin A punctuation, this brings fonts to a grand total of 146.90 KB. Not bad, and I think very worth updating to for all the improvements listed above. Of course, there might be even better strategies, like the https://github.com/Munter/subfont project you pointed to on Twitter. 

Let me know if you have any thoughts on the approach here – I know that you know a lot more about web dev & perf that I do; I'm just trying to help make sure the typography is as good as it can be. :)

**Comment by arrowtype** [comment]
Okay, two updates to the Basic English file, and (I think) I'm done.

1. It was a pretty bad idea to restrict the Basic English font to characters used on the homepage, because that excluded less-common characters like `Q` and `Z`. 😬 I've changed back to a Unicode's Basic Latin block, plus the few extra essentials.
1. pyftsubset includes alternates required to support a number of OpenType features, and an extra arg is required to ask it not to. https://github.com/fonttools/fonttools/blob/a37dab38243d8c1e88ab83376a80942012bbab48/Lib/fontTools/subset/__init__.py#L154. I've subtracted out `numr,dnom,frac` and this prevents the tiny numbers from hitching a ride. Note: if you think these are likely needed in some posts (e.g. for footnotes, etc), we should probably add them to Latin A Punc.

Result: the Basic English subset is now 124KB. Not bad!

**Comment by siakaramalegos** [comment]
Thanks for all the work! I'm going to need to make some adjustments for load UI performance. I preloaded the font before, but now that it's in various subsets, I'll need to figure out what to preload on a page to get rid of the font shifts as each font loads. This is more complex since it will vary by page now.

**Comment by arrowtype** [comment]
Ohh good point. I don't properly understand font preloading, but my best guess is:

The front page only really requires the Basic English and "sia" subsets to render – and the Basic English subset contains very few no additional characters beyond what is used there. So, these are likely worth preloading.

The other subsets could then load in normally, and fill in tiny gaps like diacritics in names or the occasional uncommon punctuation/math symbol. This would barely (if at all) shift layout and simply enhance the details for people that really read closely.

**Pull request merged**
